
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace SampleRegression.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            SampleRegression.ModelInput sampleData = new SampleRegression.ModelInput()
            {
                Snapped_at = @"2023-05-19 00:00:00 UTC",
                Market_cap = 521470752259,
                Total_volume = 13726396059,
            };

            Console.WriteLine("Using model to make single prediction -- Comparing actual Price with predicted Price from sample data...\n\n");


            Console.WriteLine($"Snapped_at: {sampleData.Snapped_at}");
            Console.WriteLine($"Price: {sampleData.Price}");
            Console.WriteLine($"Market_cap: {sampleData.Market_cap}");
            Console.WriteLine($"Total_volume: {sampleData.Total_volume}");



            // Use the model and Prediction Engine to predict on new sample data
            var predictionResult = SampleRegression.Predict(sampleData);

            Console.WriteLine($"\n\nPredicted Price: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
